language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -e .  # needed to import itself
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install black
# command to run tests
script:
  - pytest --cov=library --cov=testing
  - black --check library testing setup.py
after_success:
  - coveralls