# Set up xvfb to run my tests with a GUI
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
dist: xenial
services:
  - xvfb

language: python
python:
  - "3.7"
  - "3.8"
# installation of needed libraries for Qt
# https://github.com/pytest-dev/pytest-qt/issues/266
# Also here:
#https://github.com/qutebrowser/qutebrowser/issues/5237#issuecomment-625448697
before_install:
  - sudo apt-get install -y libxkbcommon-x11-0
  - sudo apt-get install -y libxcb-icccm4
  - sudo apt-get install -y libxcb-image0
#  - sudo apt-get install -y libxcb-keysyms1
  - sudo apt-get install -y libxcb-randr0
  - sudo apt-get install -y libxcb-render-util0
  - sudo apt-get install -y libxcb-xinerama0
install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-qt
  - pip install coveralls
  - pip install black
# commands to run tests
script:
  - pytest --cov=library --cov=testing
  - black --check library testing setup.py run.py
# then upload successful ones to coveralls to document coverage
after_success:
  - coveralls