language: python
python:
  - "3.7"
# Install some things for pyside2: https://github.com/pytest-dev/pytest-qt/issues/266
before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
# command to install dependencies
install:
  - pip install -e .  # needed to import itself
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-qt
  - pip install coveralls
  - pip install black
# command to run tests
script:
  - pytest --cov=library --cov=testing
  - black --check library testing setup.py
after_success:
  - coveralls