dist: xenial
services:
  - xvfb
language: python
python:
  - "3.7"
# attempted installation of needed libraries for Qt
before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
# command to install dependencies
install:
  - pip install -e .  # needed to import itself
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-qt
  - pip install coveralls
  - pip install black
  - python -c 'from PySide2.QtWidgets import QApplication; QApplication([])'
# command to run tests
script:
  - pytest --cov=library --cov=testing
  - black --check library testing setup.py
after_success:
  - coveralls