tremonti_bibcode = "2004ApJ...613..898T"
my_bibcode = "2018ApJ...864...94B"
my_ads_url = "https://ui.adsabs.harvard.edu/abs/{}/abstract".format(my_bibcode)
my_arxiv_id = "1804.09819"
my_arxiv_url = f"https://arxiv.org/abs/{my_arxiv_id}"
my_arxiv_url_v2 = f"https://arxiv.org/abs/{my_arxiv_id}v2"
my_arxiv_pdf_url = f"https://arxiv.org/pdf/{my_arxiv_id}.pdf"
my_arxiv_pdf_url_v2 = f"https://arxiv.org/pdf/{my_arxiv_id}v2.pdf"
my_bibtex = (
    "@ARTICLE{2018ApJ...864...94B,\n"
    "       author = {{Brown}, Gillen and {Gnedin}, Oleg Y. and {Li}, Hui},\n"
    '        title = "{Nuclear Star Clusters in Cosmological Simulations}",\n'
    "      journal = {\\apj},\n"
    "     keywords = {galaxies: formation, galaxies: nuclei, galaxies: star clusters: general, globular clusters: general, Astrophysics - Astrophysics of Galaxies, Astrophysics - Solar and Stellar Astrophysics},\n"
    "         year = 2018,\n"
    "        month = sep,\n"
    "       volume = {864},\n"
    "       number = {1},\n"
    "          eid = {94},\n"
    "        pages = {94},\n"
    "          doi = {10.3847/1538-4357/aad595},\n"
    "archivePrefix = {arXiv},\n"
    "       eprint = {1804.09819},\n"
    " primaryClass = {astro-ph.GA},\n"
    "       adsurl = {https://ui.adsabs.harvard.edu/abs/2018ApJ...864...94B},\n"
    "      adsnote = {Provided by the SAO/NASA Astrophysics Data System}\n"
    "}\n\n"
)
