name: Coverage
# Runs tests, then does coverage checks. I don't do coverage checks in the main testing
# action, since I have a matrix there to run on linux, Mac, and various python versions.
# I only need to check coverage once. Most of this duplicates test.yaml 
on:
  push:
    branches:
    - main
jobs:
  coverage:
    # I would like to use ubuntu-latest, but it uses 20.04, which has an older
    # version of SQLite that does not support removing columns.
    runs-on: ubuntu-22.04
    env: 
      ADS_DEV_KEY: ${{ secrets.ADS_DEV_KEY }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: install Qt
        uses: jurplel/install-qt-action@v3
      - name: install library
        run: pip install -e .[test]
      - name: run pytest
        uses: GabrielBB/xvfb-action@v1
        with:
          run: coverage run -m pytest
      - name: make lcov file for Coveralls upload
        run: coverage lcov -i
      - name: upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
