name: run-tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env: 
      ADS_DEV_KEY: ${{ secrets.ADS_DEV_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: jurplel/install-qt-action@v3
      - run: pip install -e .
      - run: pip install pytest
      - run: pip install pytest-cov
      - run: pip install pytest-qt
      - name: run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pytest --cov=library --cov=testing
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install black
      - run: black --check library testing setup.py run.py
